EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.example.com'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'user@example.com'
EMAIL_HOST_USER = 'user@example.com'
EMAIL_HOST_PASSWORD = 'smtp.password'
SECRET_KEY="[16/May/2021 19:28:23] GET /accounts/signup/ HTTP/1.1 200 7894"
ENV='local|production'

STRIPE_PUBLIC_TEST='pk_test_'
STRIPE_SECRET_TEST='sk_test_'


STRIPE_PUBLIC = STRIPE_PUBLIC_TEST
STRIPE_SECRET = STRIPE_SECRET_TEST

CAPTCHA_SITE   = '6Lc56D4hAAAAAC4EGOJPwbdVjRCSQGSoHGq8rMEC'
CAPTCHA_SECRET = '6Lc56D4hAAAAADXME6UCJ5MPIrG7BaSTS5eg3iJj'

# -- SIngle Sign on below
OIDC_RP_CLIENT_ID = ''
OIDC_RP_CLIENT_SECRET = ''
OIDC_OP_AUTHORIZATION_ENDPOINT = ''
OIDC_OP_TOKEN_ENDPOINT = ''
OIDC_OP_USER_ENDPOINT = ''
OIDC_RP_SIGN_ALGO = ''
OIDC_OP_JWKS_ENDPOINT = ''
OIDC_RP_SCOPES = ''
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 15

OIDC_CREATE_USER = True
OIDC_VERIFY_SSL = True

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


DEFAULT_DOMAIN="http://www.example.com"